@ECHO OFF
ECHO FIRST-RUN.CMD IS USED TO SETUP YOUR PROJECT PROPERLY FOR THE FIRST-TIME USE.
ECHO ---------
ECHO SETTING UP PROJECT
ECHO __________
ECHO 1- DEPENDENCIES
ECHO --------------
cd client
npm i --save
ECHO DEPENDENCIES DONE.
ECHO __________
ECHO 2- SETTING UP SMART CONTRACTS
cd ..
truffle migrate --reset --network mobile_develop.
ECHO SMART CONTRACTS ARE SET.
ECHO ALL SET, TO RUN YOUR APPLICATION EXECUTE RUN.CMD
