@ECHO OFF
ECHO DESCRIPTION: RUN.CMD IS USED TO RUN YOUR APPLICATION, IF YOU ARE RUNNING IT FOR THE FIRST TIME USE FIRST-RUN.CMD INSTEAD.
ECHO --------
ECHO RUNNING APPLICATION
ECHO --------
cd client
npm start
